1 app request monitoring (#5)
* initial dashboards, datasources, and compose

diff --git a/labtastic b/labtastic
--- a/labtastic
+++ b/labtastic
@@ -34,15 +34,17 @@ labtastic_usage() {
   echo
   # :command.usage_commands
   printf "Commands:\n"
-  echo "  init      Initialize Labtastic"
-  echo "  install   install and prepare an app"
-  echo "  start     start an app"
-  echo "  stop      stop an app"
-  echo "  up        start an app"
-  echo "  down      stop an app"
-  echo "  status    show status of all containers"
-  echo "  logs      tail logs of give app container"
-  echo "  update    update labtastic"
+  echo "  init       Initialize Labtastic"
+  echo "  install    install and prepare an app"
+  echo "  start      start an app"
+  echo "  stop       stop an app"
+  echo "  up         start an app"
+  echo "  down       stop an app"
+  echo "  down-all   stop all apps"
+  echo "  up-all     start all apps"
+  echo "  status     show status of all containers"
+  echo "  logs       tail logs of give app container"
+  echo "  update     update labtastic"
   echo
 
   if [[ -n $long_usage ]]; then
@@ -316,6 +318,72 @@ labtastic_down_usage() {
 }
 
 # :command.usage
+labtastic_down_all_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "labtastic down-all - stop all apps\n"
+    echo
+
+  else
+    printf "labtastic down-all - stop all apps\n"
+    echo
+
+  fi
+
+  printf "Usage:\n"
+  printf "  labtastic down-all\n"
+  printf "  labtastic down-all --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "Examples:\n"
+
+    printf "  labtastic down-all\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+labtastic_up_all_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "labtastic up-all - start all apps\n"
+    echo
+
+  else
+    printf "labtastic up-all - start all apps\n"
+    echo
+
+  fi
+
+  printf "Usage:\n"
+  printf "  labtastic up-all\n"
+  printf "  labtastic up-all --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "Examples:\n"
+
+    printf "  labtastic up-all\n"
+    echo
+
+  fi
+}
+
+# :command.usage
 labtastic_status_usage() {
   if [[ -n $long_usage ]]; then
     printf "labtastic status - show status of all containers\n"
@@ -477,13 +545,20 @@ setup_app() {
   app_name=$1
 
   source .env.apps
+  source .env
 
   if printf '%s\0' "${ENABLED_APPS[@]}" | grep -Fxqz "$app_name"; then
     error "app already installed"
     exit 1
+
   fi
 
-  echo "ENABLED_APPS+=(\"$1\")" >> .env.apps
+  NEW_APPS=""
+  for app in ${ENABLED_APPS[@]}; do
+    NEW_APPS="${NEW_APPS} \"$app\""
+  done
+  NEW_APPS="${NEW_APPS} \"$app_name\""
+  echo "ENABLED_APPS=($NEW_APPS)" > .env.apps
   echo "# $1 Vars" >> .env
   cat "apps/$1/.env" >> .env
   echo "" >> .env
@@ -535,62 +610,41 @@ generate_compose_files_list() {
   files=""
 
   for app in ${ENABLED_APPS[@]}; do
-      files="-f apps/${ENABLED_APPS[$app]}/docker-compose.yml "
+      files="$files -f apps/$app/docker-compose.yml"
   done
 
   echo $files
 }
 
-generate_compose_profiles() {
-  source .env.apps
-
-  profiles=""
-
-  for app in ${!ENABLED_APPS[@]}; do
-    if [[ $app -eq 1 ]]; then
-      files="${ENABLED_APPS[$app]}"
-    else
-      files="${files},${ENABLED_APPS[$app]}"
-    fi
-  done
-
-  echo $profiles
-}
-
 docker_compose_setup() {
-  compose_files=$(generate_compose_files_list)
-  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" |  xargs ) docker compose --project-name labtastic --profile "$1-setup" ${compose_files} up -d
+  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" |  xargs ) docker compose --project-name labtastic --profile "$1-setup" -f apps/${1}/docker-compose.yml up -d
 }
 
 docker_compose_up() {
+  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" | xargs ) docker compose --project-name labtastic -f apps/${1}/docker-compose.yml up -d
+}
+
+docker_compose_up_all() {
   compose_files=$(generate_compose_files_list)
-  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" | xargs ) docker compose --project-name labtastic --profile "$1" ${compose_files} up -d
+  echo $compose_files
+  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" | xargs ) docker compose --project-name labtastic ${compose_files} up -d
 }
 
 docker_compose_down() {
-  compose_files=$(generate_compose_files_list)
-  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" | xargs ) docker compose --project-name labtastic --profile "$1" ${compose_files} down
+  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" | xargs ) docker compose --project-name labtastic -f apps/${1}/docker-compose.yml down
 }
 
-docker_compose_stop_all() {
+docker_compose_down_all() {
   compose_files=$(generate_compose_files_list)
-  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" | xargs ) docker compose --project-name labtastic --profile "$app" ${compose_files} stop
+  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" | xargs ) docker compose --project-name labtastic ${compose_files} down
 }
 
 docker_compose_stop() {
-  compose_files=$(generate_compose_files_list)
-  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" | xargs ) docker compose --project-name labtastic --profile "$1" ${compose_files} stop
-}
-
-docker_compose_start_all() {
-  compose_files=$(generate_compose_files_list)
-  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" | xargs ) docker compose --project-name labtastic --profile "$app" ${compose_files}l start
-
+  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" | xargs ) docker compose --project-name labtastic -f apps/${1}/docker-compose.yml stop
 }
 
 docker_compose_start() {
-  compose_files=$(generate_compose_files_list)
-  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" | xargs ) docker compose --project-name labtastic --profile "$1" ${compose_files} start
+  env $(cat .env | grep -v "^#" | grep -v "ENABLED_APPS" | xargs ) docker compose --project-name labtastic -f apps/${1}/docker-compose.yml start
 }
 
 docker_compose_status() {
@@ -600,7 +654,7 @@ docker_compose_status() {
 
 docker_compose_logs() {
   compose_files=$(generate_compose_files_list)
-  env $(cat .env | grep -v "^#" | xargs ) docker compose --project-name labtastic --profile "$1" ${compose_files} logs -f "$2"
+  env $(cat .env | grep -v "^#" | xargs ) docker compose --project-name labtastic ${compose_files} logs -f "$1"
 }
 
 # src/lib/filters.sh
@@ -665,8 +719,17 @@ labtastic_init_command() {
     info "Installing docker..."
     curl -fsSL https://get.docker.com | bash
     sudo usermod -A -G docker "$(whoami)"
+    echo '{"metrics-addr" : "0.0.0.0:9323", "experimental" : true}' | sudo tee /etc/docker/daemon.json
+    sudo systemctl restart docker.service
   else
     info "docker already installed"
+    if [ -f "/etc/docker/daemon.json" ]; then
+      warn "Please insure that the following settings are added to /etc/docker/daemon.json"
+      warn '{"metrics-addr" : "0.0.0.0:9323", "experimental" : true}'
+    else
+      echo '{"metrics-addr" : "0.0.0.0:9323", "experimental" : true}' | sudo tee /etc/docker/daemon.json
+      sudo systemctl restart docker.service
+    fi
   fi
 
   docker network create --subnet "10.255.0.0/16" --attachable labtastic
@@ -713,10 +776,10 @@ labtastic_install_command() {
     exit 0
   fi
 
-  docker_compose_setup "${args[appname]}"
+  # docker_compose_setup "${args[appname]}"
 
   info "setup for ${args[appname]} app finished!"
-  info "please run './labtastic app ${args[appname]} --start' to finish installation"
+  info "please run './labtastic up ${args[appname]}' to finish installation"
 }
 
 # :command.function
@@ -741,6 +804,18 @@ labtastic_up_command() {
 labtastic_down_command() {
   # src/down_command.sh
   docker_compose_down "${args[appname]}"
+}
+
+# :command.function
+labtastic_down_all_command() {
+  # src/down_all_command.sh
+  docker_compose_down_all
+}
+
+# :command.function
+labtastic_up_all_command() {
+  # src/up_all_command.sh
+  docker_compose_up_all "${args[appname]}"
 }
 
 # :command.function
@@ -830,6 +905,20 @@ parse_requirements() {
     action="down"
     shift
     labtastic_down_parse_requirements "$@"
+    shift $#
+    ;;
+
+  down-all )
+    action="down-all"
+    shift
+    labtastic_down_all_parse_requirements "$@"
+    shift $#
+    ;;
+
+  up-all )
+    action="up-all"
+    shift
+    labtastic_up_all_parse_requirements "$@"
     shift $#
     ;;
 
@@ -1198,6 +1287,90 @@ labtastic_down_parse_requirements() {
 }
 
 # :command.parse_requirements
+labtastic_down_all_parse_requirements() {
+  # :command.fixed_flags_filter
+  case "${1:-}" in
+  --help | -h )
+    long_usage=yes
+    labtastic_down_all_usage
+    exit
+    ;;
+
+  esac
+  # :command.environment_variables_filter
+  # :command.dependencies_filter
+  # :command.command_filter
+  action="down-all"
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+    -?* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+
+    * )
+      # :command.parse_requirements_case
+      # :command.parse_requirements_case_simple
+      printf "invalid argument: %s\n" "$key"
+      exit 1
+      ;;
+
+    esac
+  done
+  # :command.required_args_filter
+  # :command.required_flags_filter
+  # :command.catch_all_filter
+  # :command.default_assignments
+  # :command.whitelist_filter
+  # :command.user_filter
+}
+
+# :command.parse_requirements
+labtastic_up_all_parse_requirements() {
+  # :command.fixed_flags_filter
+  case "${1:-}" in
+  --help | -h )
+    long_usage=yes
+    labtastic_up_all_usage
+    exit
+    ;;
+
+  esac
+  # :command.environment_variables_filter
+  # :command.dependencies_filter
+  # :command.command_filter
+  action="up-all"
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+    -?* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+
+    * )
+      # :command.parse_requirements_case
+      # :command.parse_requirements_case_simple
+      printf "invalid argument: %s\n" "$key"
+      exit 1
+      ;;
+
+    esac
+  done
+  # :command.required_args_filter
+  # :command.required_flags_filter
+  # :command.catch_all_filter
+  # :command.default_assignments
+  # :command.whitelist_filter
+  # :command.user_filter
+}
+
+# :command.parse_requirements
 labtastic_status_parse_requirements() {
   # :command.fixed_flags_filter
   case "${1:-}" in
@@ -1404,6 +1577,22 @@ run() {
       labtastic_down_usage
     else
       labtastic_down_command
+    fi
+
+  elif [[ $action == "down-all" ]]; then
+    if [[ ${args[--help]:-} ]]; then
+      long_usage=yes
+      labtastic_down_all_usage
+    else
+      labtastic_down_all_command
+    fi
+
+  elif [[ $action == "up-all" ]]; then
+    if [[ ${args[--help]:-} ]]; then
+      long_usage=yes
+      labtastic_up_all_usage
+    else
+      labtastic_up_all_command
     fi
 
   elif [[ $action == "status" ]]; then
