start and stop commands

diff --git a/labtastic b/labtastic
--- a/labtastic
+++ b/labtastic
@@ -36,7 +36,8 @@ labtastic_usage() {
   printf "Commands:\n"
   echo "  init      Initialize Labtastic"
   echo "  install   install and prepare an app"
-  echo "  app       start/stop an app"
+  echo "  start     start an app"
+  echo "  stop      stop an app"
   echo "  update    update labtastic"
   echo
 
@@ -147,20 +148,20 @@ labtastic_install_usage() {
 }
 
 # :command.usage
-labtastic_app_usage() {
+labtastic_start_usage() {
   if [[ -n $long_usage ]]; then
-    printf "labtastic app - start/stop an app\n"
+    printf "labtastic start - start an app\n"
     echo
 
   else
-    printf "labtastic app - start/stop an app\n"
+    printf "labtastic start - start an app\n"
     echo
 
   fi
 
   printf "Usage:\n"
-  printf "  labtastic app APPNAME [options]\n"
-  printf "  labtastic app --help | -h\n"
+  printf "  labtastic start APPNAME\n"
+  printf "  labtastic start --help | -h\n"
   echo
 
   if [[ -n $long_usage ]]; then
@@ -169,29 +170,60 @@ labtastic_app_usage() {
     echo "  --help, -h"
     printf "    Show this help\n"
     echo
-    # :command.usage_flags
-    # :flag.usage
-    echo "  --start"
-    printf "    start the given app\n"
-    echo
 
-    # :flag.usage
-    echo "  --stop"
-    printf "    stop the given app\n"
-    echo
     # :command.usage_args
     printf "Arguments:\n"
 
     # :argument.usage
     echo "  APPNAME"
-    printf "    name of app to be used\n"
+    printf "\n"
     echo
 
     # :command.usage_examples
     printf "Examples:\n"
 
-    printf "  labtastic app app-name --start\n"
-    printf "  labtastic app app-name --stop\n"
+    printf "  labtastic start app-name\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+labtastic_stop_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "labtastic stop - stop an app\n"
+    echo
+
+  else
+    printf "labtastic stop - stop an app\n"
+    echo
+
+  fi
+
+  printf "Usage:\n"
+  printf "  labtastic stop APPNAME\n"
+  printf "  labtastic stop --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "Arguments:\n"
+
+    # :argument.usage
+    echo "  APPNAME"
+    printf "\n"
+    echo
+
+    # :command.usage_examples
+    printf "Examples:\n"
+
+    printf "  labtastic start app-name\n"
     echo
 
   fi
@@ -479,23 +511,15 @@ labtastic_install_command() {
 }
 
 # :command.function
-labtastic_app_command() {
-  # src/app_command.sh
-  if [[ ${args[--stop]} ]]; then
-    if [ "${args[appname]}" == "all" ]; then
-      docker_compose_stop_all
-    else
-      docker_compose_stop "${args[appname]}"
-    fi
-  fi
+labtastic_start_command() {
+  # src/start_command.sh
+  docker_compose_start "${args[appname]}"
+}
 
-  if [[ ${args[--start]} ]]; then
-    if [ "${args[appname]}" == "all" ]; then
-      docker_compose_start_all
-    else
-      docker_compose_start "${args[appname]}"
-    fi
-  fi
+# :command.function
+labtastic_stop_command() {
+  # src/stop_command.sh
+  docker_compose_stop "${args[appname]}"
 }
 
 # :command.function
@@ -548,10 +572,17 @@ parse_requirements() {
     shift $#
     ;;
 
-  app )
-    action="app"
+  start )
+    action="start"
     shift
-    labtastic_app_parse_requirements "$@"
+    labtastic_start_parse_requirements "$@"
+    shift $#
+    ;;
+
+  stop )
+    action="stop"
+    shift
+    labtastic_stop_parse_requirements "$@"
     shift $#
     ;;
 
@@ -698,12 +729,12 @@ labtastic_install_parse_requirements() {
 }
 
 # :command.parse_requirements
-labtastic_app_parse_requirements() {
+labtastic_start_parse_requirements() {
   # :command.fixed_flags_filter
   case "${1:-}" in
   --help | -h )
     long_usage=yes
-    labtastic_app_usage
+    labtastic_start_usage
     exit
     ;;
 
@@ -711,34 +742,11 @@ labtastic_app_parse_requirements() {
   # :command.environment_variables_filter
   # :command.dependencies_filter
   # :command.command_filter
-  action="app"
+  action="start"
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-    # :flag.case
-    --start )
-      # :flag.conflicts
-      if [[ -n "${args[--stop]:-}" ]]; then
-        printf "conflicting options: %s cannot be used with %s\n" "$key" "--stop"
-        exit 1
-      fi
-      # :flag.case_no_arg
-      args[--start]=1
-      shift
-      ;;
-
-    # :flag.case
-    --stop )
-      # :flag.conflicts
-      if [[ -n "${args[--start]:-}" ]]; then
-        printf "conflicting options: %s cannot be used with %s\n" "$key" "--start"
-        exit 1
-      fi
-      # :flag.case_no_arg
-      args[--stop]=1
-      shift
-      ;;
 
     -?* )
       printf "invalid option: %s\n" "$key"
@@ -762,7 +770,59 @@ labtastic_app_parse_requirements() {
   done
   # :command.required_args_filter
   if [[ -z ${args[appname]+x} ]]; then
-    printf "missing required argument: APPNAME\nusage: labtastic app APPNAME [options]\n"
+    printf "missing required argument: APPNAME\nusage: labtastic start APPNAME\n"
+    exit 1
+  fi
+  # :command.required_flags_filter
+  # :command.catch_all_filter
+  # :command.default_assignments
+  # :command.whitelist_filter
+  # :command.user_filter
+}
+
+# :command.parse_requirements
+labtastic_stop_parse_requirements() {
+  # :command.fixed_flags_filter
+  case "${1:-}" in
+  --help | -h )
+    long_usage=yes
+    labtastic_stop_usage
+    exit
+    ;;
+
+  esac
+  # :command.environment_variables_filter
+  # :command.dependencies_filter
+  # :command.command_filter
+  action="stop"
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+    -?* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+
+    * )
+      # :command.parse_requirements_case
+      # :command.parse_requirements_case_simple
+      if [[ -z ${args[appname]+x} ]]; then
+        # :argument.validations
+        args[appname]=$1
+        shift
+      else
+        printf "invalid argument: %s\n" "$key"
+        exit 1
+      fi
+      ;;
+
+    esac
+  done
+  # :command.required_args_filter
+  if [[ -z ${args[appname]+x} ]]; then
+    printf "missing required argument: APPNAME\nusage: labtastic stop APPNAME\n"
     exit 1
   fi
   # :command.required_flags_filter
@@ -847,12 +907,20 @@ run() {
       labtastic_install_command
     fi
 
-  elif [[ $action == "app" ]]; then
+  elif [[ $action == "start" ]]; then
     if [[ ${args[--help]:-} ]]; then
       long_usage=yes
-      labtastic_app_usage
+      labtastic_start_usage
     else
-      labtastic_app_command
+      labtastic_start_command
+    fi
+
+  elif [[ $action == "stop" ]]; then
+    if [[ ${args[--help]:-} ]]; then
+      long_usage=yes
+      labtastic_stop_usage
+    else
+      labtastic_stop_command
     fi
 
   elif [[ $action == "update" ]]; then
